/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import HashTA.*;
import javax.swing.JOptionPane;
        
/**
 *
 * @author yangel/OROZCO/VIVOLO
 */
public class Búsqueda extends javax.swing.JFrame {
    private TablaHash miTabla;
    /**
     * Creates new form Búsqueda
     */
    //@TablaHash Tabla
    public Búsqueda() {
        this.setSize(507, 309);
        this.miTabla = GestorCSV.getTablaHash();
        this.setTitle("Busqueda de Clientes");
        this.setLocationRelativeTo(null);
    
    initComponents();
    
    BBoton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buscarActionPerformed(evt);
        }
    });
    }   
    public void setTablaHash(TablaHash tabla) {
        this.miTabla = tabla;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BBoton = new javax.swing.JButton();
        Last_nameF = new javax.swing.JTextField();
        L_nameF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exitB = new javax.swing.JButton();
        VolverB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        BTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BTable);

        jLabel1.setText("Busqueda de Clientes");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 6, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 656, 415, -1));

        jLabel2.setText("Busqueda de Clientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 130, -1));

        BBoton.setText("Buscar");
        BBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBotonActionPerformed(evt);
            }
        });
        getContentPane().add(BBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        Last_nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_nameFActionPerformed(evt);
            }
        });
        getContentPane().add(Last_nameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));

        L_nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_nameFActionPerformed(evt);
            }
        });
        getContentPane().add(L_nameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, -1));

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, -1));

        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 20));

        exitB.setText("X");
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });
        getContentPane().add(exitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        VolverB.setText("Volver");
        VolverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBActionPerformed(evt);
            }
        });
        getContentPane().add(VolverB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBActionPerformed

    private void VolverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBActionPerformed
        // TODO add your handling code here:
        Menú ventana = new Menú();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverBActionPerformed

    private void Last_nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_nameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_nameFActionPerformed

    private void L_nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_nameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_nameFActionPerformed

    private void BBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBotonActionPerformed
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) { 
    String nombre = L_nameF.getText().trim().toLowerCase();
    String apellido = Last_nameF.getText().trim().toLowerCase();
    this.miTabla = GestorCSV.getTablaHash();
 
    Estado resultado = miTabla.buscar(nombre, apellido);
    miTabla.imprimirTablaHash();
    if (resultado != null) {
        JOptionPane.showMessageDialog(this, "Número de habitación encontrado: " + resultado.numHab);
    } else {
        JOptionPane.showMessageDialog(this, "Registro no encontrado.");
    }
}

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBoton;
    private javax.swing.JTable BTable;
    private javax.swing.JTextField L_nameF;
    private javax.swing.JTextField Last_nameF;
    private javax.swing.JButton VolverB;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
