package Interfaz;

import ABB_LE.*;
import Objetos.Habitación;
import Objetos.Histórico;
import Objetos.Reservación;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class Registro1 extends javax.swing.JFrame {

    private JTable tableHabitaciones;
    private DefaultTableModel mt;
    private Reservación reservas; // Asegúrate de inicializar esto

    private Habitaciones habitaciones;


    /**
     * Creates new form Registro
     */
    public Registro1() {
        this.setSize(726, 223);
        this.setTitle("Busqueda de Reserva");
        this.setLocationRelativeTo(null);

        mt = new DefaultTableModel();
        mt.addColumn("CI");
        mt.addColumn("Primer_nombre");
        mt.addColumn("Segundo_nombre");
        mt.addColumn("Email");
        mt.addColumn("Genero");
        mt.addColumn("Tipo_Hab");
        mt.addColumn("celular");
        mt.addColumn("Llegada");
        mt.addColumn("Salida");

        tableHabitaciones = new JTable(mt);

        JScrollPane scrollPane = new JScrollPane(tableHabitaciones);
        getContentPane().add(scrollPane);

        
CiBusqueda.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String cedula = CiField.getText();
        Reservación reservacion = habitaciones.buscarReservaciónPorCedula(cedula);

        if (reservacion != null) {
            // Agregar fila a la tabla con los datos de la reservación encontrada
            Object[] fila = {
                reservacion.getCi(),
                reservacion.getNombre(),
                reservacion.getApellido(),
                reservacion.getEmail(),
                reservacion.getGénero(),
                reservacion.getTipoHab(),
                reservacion.getCelular(),
                reservacion.getLlegada(),
                reservacion.getSalida()
            };
            mt.addRow(fila);
        } else {
            System.out.println("No se encontró reservación para la cédula " + cedula);
        }
    }
});

}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CiBusqueda = new javax.swing.JButton();
        CiField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reserva = new javax.swing.JTable();
        VolverR = new javax.swing.JButton();
        Xreserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Busqueda de reservación:");

        CiBusqueda.setText("Buscar");
        CiBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiBusquedaActionPerformed(evt);
            }
        });

        CiField.setText("C.I");

        jLabel2.setText("Cedula de identidad:");

        Reserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.I.", "Primer_nombre", "Segundo_nombre", "Genero", "Tipo_hab", "celular", "Llegada", "Salida"
            }
        ));
        jScrollPane1.setViewportView(Reserva);

        VolverR.setText("Volver");
        VolverR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverRActionPerformed(evt);
            }
        });

        Xreserva.setText("X");
        Xreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XreservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(CiField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CiBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(VolverR, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Xreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Xreserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CiBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(VolverR)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XreservaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_XreservaActionPerformed

    private void VolverRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverRActionPerformed
        // TODO add your handling code here:
        Menú ventana = new Menú();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverRActionPerformed

    private void CiBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiBusquedaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CiBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CiBusqueda;
    private javax.swing.JTextField CiField;
    private javax.swing.JTable Reserva;
    private javax.swing.JButton VolverR;
    private javax.swing.JButton Xreserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
